import numpy as np
import matplotlib.pyplot as plt

TIME_switch,MSD_switch,FO_switch,FSX_switch,FSY_switch,FSZ_switch = np.loadtxt("output_switch.dat",delimiter=',',unpack=True,dtype=np.double)
TIME,MSD,FO,FSX,FSY,FSZ = np.loadtxt("output_new.dat",delimiter=',',unpack=True,dtype=np.double)
TIME_old,MSD_old,FO_old,FSX_old,FSY_old,FSZ_old = np.loadtxt("output_old.dat",delimiter=',',unpack=True,dtype=np.double)

plt.scatter(TIME_switch,MSD_switch)
plt.scatter(TIME,MSD)
plt.scatter(TIME_old,MSD_old)
plt.yscale("log")
plt.xscale("log")
plt.xlim(left=100)
#plt.ylim(bottom=0.1)
plt.legend(["HOOMD switch","new analysis","old analysis"])
plt.title("Mean squared displacement")
plt.xlabel("mc steps")
plt.ylabel("msd")
plt.savefig("msd.png")
plt.clf()

plt.scatter(TIME_switch,FO_switch)
plt.scatter(TIME,FO)
plt.scatter(TIME_old,FO_old)
#plt.yscale("log")
plt.legend(["HOOMD switch","new analysis","old analysis"])
plt.xscale("log")
plt.title("overlap function")
plt.xlabel("mc steps")
plt.ylabel("f_o")
plt.savefig("fo.png")
plt.clf()
